name: deploy-frontend
on:
  push: 
    branches:
      - master
    paths:
      - frontend/**
      - .github/workflows/deploy-frontend.yaml

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GHCR_REPO: ${{ vars.GHCR_REPO }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - uses: gitleaks/gitleaks-action@v2
        with:
          args: "--redact --verbose"
      
      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-${{ runner.os }}-${{ hashFiles('**/package-lock.json','**/go.sum') }}
          restore-keys: trivy-${{ runner.os }}-

      - name: Trivy FS scan (fail on High/Critical)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          format: table
          severity: ${{ env.VULN_SEVERITY }}
          exit-code: '1'
  
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.GHCR_REPO }}:${{ github.sha }}
            ${{ env.GHCR_REPO }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max